<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany; // Import HasMany

use Illuminate\Database\Eloquent\Relations\HasManyThrough; // Import HasManyThrough
use App\Models\User; // Required for relationships
use App\Models\ShortUrl; // Required for relationships

class Company extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name', 'email', 'owner_user_id', 'created_at', 'updated_at'
    ];

    /**
     * Get the user that owns the company (the owner).
     *
     * @return BelongsTo
     */
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class, 'owner_user_id');
    }

    /**
     * Get the users/members belonging to the company.
     * * NOTE: This assumes a 'company_id' column exists on the 'users' table.
     *
     * @return HasMany
     */
    public function members(): HasMany
    {
        return $this->hasMany(User::class, 'company_id');
    }

    /**
     * Get all short URLs generated by members of this company.
     *
     * @return HasManyThrough
     */
    public function shortUrls(): HasManyThrough
    {
        // 1st argument: Final model (ShortUrl)
        // 2nd argument: Intermediate model (User)
        // 3rd argument: Foreign key on intermediate table (users.company_id)
        // 4th argument: Foreign key on final table (short_urls.user_id)
        return $this->hasManyThrough(ShortUrl::class, User::class, 'company_id', 'user_id');
    }

    /**
     * Get the total count of members in this company.
     *
     * @return int
     */
    public function totalMemberCount(): int
    {
        return $this->members()->count();
    }

    /**
     * Get the total number of short URLs generated by all members of the company.
     *
     * @return int
     */
    public function totalGeneratedUrlsCount(): int
    {
        return $this->shortUrls()->count();
    }

    /**
     * Get the total number of accesses (clicks) for all short URLs generated by the company's members.
     * Assumes the ShortUrl model has an 'access_count' column.
     *
     * @return int
     */
    public function totalShortUrlAccesses(): int
    {
        // Sums the 'access_count' column across all related short URLs.
        return (int) $this->shortUrls()->sum('access_count');
    }
}